import { Product, Category } from './types';

export const CATEGORIES: Category[] = [
  {
    id: 'griferia',
    name: 'Grifería',
    icon: '🚿',
    image: 'https://images.unsplash.com/photo-1584622650111-993a426fbf0a?auto=format&fit=crop&q=80&w=600',
    description: 'Monocomandos, duchas y accesorios de alta calidad',
  },
  {
    id: 'pisos',
    name: 'Pisos y Revestimientos',
    icon: '🧱',
    image: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?auto=format&fit=crop&q=80&w=600',
    description: 'Porcelanatos, cerámicas y revestimientos para cada ambiente',
  },
  {
    id: 'sanitarios',
    name: 'Sanitarios',
    icon: '🚽',
    image: 'https://images.unsplash.com/photo-1552321554-5fefe8c9ef14?auto=format&fit=crop&q=80&w=600',
    description: 'Inodoros, bidets, lavatorios y vanitorios',
  },
  {
    id: 'obra-gruesa',
    name: 'Obra Gruesa',
    icon: '🏗️',
    image: 'https://images.unsplash.com/photo-1504307651254-35680f356dfd?auto=format&fit=crop&q=80&w=600',
    description: 'Cemento, hierro, bloques y materiales estructurales',
  },
  {
    id: 'instalaciones',
    name: 'Instalaciones',
    icon: '🔧',
    image: 'https://images.unsplash.com/photo-1621905251189-08b45d6a269e?auto=format&fit=crop&q=80&w=600',
    description: 'Plomería, gas, electricidad y calefacción',
  },
  {
    id: 'hogar',
    name: 'Hogar',
    icon: '🏠',
    image: 'https://images.unsplash.com/photo-1484154218962-a197022b5858?auto=format&fit=crop&q=80&w=600',
    description: 'Muebles, decoración y productos para el hogar',
  },
  {
    id: 'pinturas',
    name: 'Pinturas',
    icon: '🎨',
    image: 'https://images.unsplash.com/photo-1562259949-e8e7689d7828?auto=format&fit=crop&q=80&w=600',
    description: 'Látex, esmaltes, selladores y revestimientos',
  },
  {
    id: 'ofertas',
    name: 'Ofertas',
    icon: '🏷️',
    image: 'https://images.unsplash.com/photo-1607082348824-0a96f2a4b9da?auto=format&fit=crop&q=80&w=600',
    description: 'Los mejores precios en productos seleccionados',
  },
];

export const PRODUCTS: Product[] = [
  {
    id: 'p1',
    name: 'Monocomando Vasser Lyra Alto Lavatorio',
    brand: 'Vasser',
    category: 'Grifería',
    subcategory: 'Baño',
    price: 184620,
    listPrice: 184620,
    cashPrice: 156927,
    installments: 9,
    installmentPrice: 20514,
    image: 'https://images.unsplash.com/photo-1584622650111-993a426fbf0a?auto=format&fit=crop&q=80&w=400',
    stock: true,
    stockStatus: 'in_stock',
    sku: 'VL-001',
    description: 'Monocomando de diseño moderno para lavatorio. Tecnología cerámica de cierre suave, cuerpo de latón de alta durabilidad. Línea Lyra Alto de Vasser, perfecta para baños contemporáneos.',
    features: ['Cierre cerámico de alta durabilidad', 'Cuerpo de latón 100%', 'Acabado cromo brillante', 'Fácil instalación', 'Garantía 5 años de fábrica'],
    isFeatured: true,
  },
  {
    id: 'p2',
    name: 'Bidet Peirano C.Cerm. Santander',
    brand: 'Peirano',
    category: 'Sanitarios',
    price: 237347,
    listPrice: 237347,
    cashPrice: 201745,
    installments: 9,
    installmentPrice: 26372,
    image: 'https://images.unsplash.com/photo-1564540586988-aa4e53c3d799?auto=format&fit=crop&q=80&w=400',
    stock: true,
    stockStatus: 'in_stock',
    sku: 'BS-021',
    description: 'Bidet de loza sanitaria de primera calidad con cierre cerámico. Diseño clásico y funcional de la línea Santander de Peirano. Compatible con inodoro de la misma línea.',
    features: ['Loza sanitaria de 1ra. calidad', 'Cierre cerámico incluido', 'Compatible con línea Santander', 'Color blanco estándar', 'Garantía fabricante'],
    isFeatured: true,
  },
  {
    id: 'p3',
    name: 'Porcelanato Cemix Dark 60x60 1ra. Cal.',
    brand: 'Cemix',
    category: 'Pisos y Revestimientos',
    subcategory: 'Porcelanatos',
    price: 181694,
    listPrice: 181694,
    cashPrice: 154440,
    installments: 9,
    installmentPrice: 20514,
    image: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?auto=format&fit=crop&q=80&w=400',
    stock: true,
    stockStatus: 'in_stock',
    sku: 'PD-060',
    description: 'Porcelanato de primera calidad en tono oscuro tipo cemento industrial. Ideal para ambientes modernos y minimalistas, tanto en interiores como exteriores cubiertos.',
    features: ['Tono oscuro tipo cemento', 'Borde rectificado de fábrica', 'Baja absorción de agua', 'Resistente a alto tránsito', 'Apto interior y exterior cubierto'],
    isNew: true,
    isFeatured: true,
  },
  {
    id: 'p4',
    name: 'Ceramica Allpa California Gris Claro 36x36',
    brand: 'Allpa',
    category: 'Pisos y Revestimientos',
    subcategory: 'Cerámicas',
    price: 215885,
    listPrice: 215885,
    cashPrice: 183602,
    installments: 9,
    installmentPrice: 21345,
    image: 'https://images.unsplash.com/photo-1615971677499-5467cbab01d5?auto=format&fit=crop&q=80&w=400',
    stock: true,
    stockStatus: 'low_stock',
    sku: 'CA-036',
    description: 'Cerámica gris claro diseño California, perfecta para ambientes luminosos. Formato 36x36 que facilita la colocación y reduce el desperdicio de material.',
    features: ['Acabado mate elegante', 'Formato 36x36 cm', 'Color gris claro uniforme', 'Baja porosidad', 'Fácil mantenimiento'],
    discount: 10,
    isFeatured: true,
  },
  {
    id: 'p5',
    name: 'Ducha Monocomando Ext. Roca L20',
    brand: 'Roca',
    category: 'Grifería',
    subcategory: 'Baño',
    price: 220921,
    listPrice: 220921,
    cashPrice: 187783,
    installments: 9,
    installmentPrice: 24547,
    image: 'https://images.unsplash.com/photo-1585704032915-c3400ca199e7?auto=format&fit=crop&q=80&w=400',
    stock: true,
    stockStatus: 'in_stock',
    sku: 'DR-L20',
    description: 'Monocomando externo para ducha de la reconocida línea L20 de Roca. Tecnología de ahorro de agua, diseño moderno y compatible con sistemas de ducha estándar.',
    features: ['Tecnología de ahorro de agua', 'Acabado cromado de alta resistencia', 'Instalación externa simplificada', 'Compatible con baterías estándar', 'Marca Roca — garantía internacional'],
    isFeatured: true,
  },
  {
    id: 'p6',
    name: 'Vanitory Schneider 80 Colgante',
    brand: 'Schneider',
    category: 'Sanitarios',
    price: 681290,
    listPrice: 681290,
    cashPrice: 579097,
    installments: 9,
    installmentPrice: 75699,
    image: 'https://images.unsplash.com/photo-1631049421450-348ccd7f8949?auto=format&fit=crop&q=80&w=400',
    stock: true,
    stockStatus: 'in_stock',
    sku: 'VS-080',
    description: 'Mueble de baño colgante de 80 cm con diseño contemporáneo. Incluye mesada con bacha integrada. Madera de alta resistencia a la humedad con herrajes de cierre suave.',
    features: ['Madera resistente a la humedad', 'Cajón con cierre suave', 'Mesada con bacha integrada', 'Sistema de montaje colgante', 'Amplia capacidad de almacenaje'],
    isNew: true,
    isFeatured: true,
  },
  {
    id: 'p7',
    name: 'Accesorios Para Baño Casal 6 Pzs. Mytho',
    brand: 'Casal',
    category: 'Grifería',
    subcategory: 'Accesorios',
    price: 142708,
    listPrice: 142708,
    cashPrice: 121302,
    installments: 9,
    installmentPrice: 15857,
    image: 'https://images.unsplash.com/photo-1620626011761-996317702149?auto=format&fit=crop&q=80&w=400',
    stock: true,
    stockStatus: 'in_stock',
    sku: 'AB-M6',
    description: 'Set completo de 6 accesorios para baño línea Mytho de Casal. Incluye toallero, portarrollo, jabonera, percha doble, repisa y gancho. Acabado cromo de alta durabilidad.',
    features: ['6 piezas completas para baño', 'Acabado cromo brillante', 'Fijación a pared incluida', 'Diseño minimalista moderno', 'Latón y zinc de alta calidad'],
    discount: 15,
    isFeatured: true,
  },
  {
    id: 'p8',
    name: 'Lavatorio Capea Italiana Grande',
    brand: 'Capea',
    category: 'Sanitarios',
    price: 74000,
    listPrice: 74000,
    cashPrice: 62890,
    installments: 9,
    installmentPrice: 8221,
    image: 'https://images.unsplash.com/photo-1552321554-5fefe8c9ef14?auto=format&fit=crop&q=80&w=400',
    stock: true,
    stockStatus: 'in_stock',
    sku: 'LC-IG',
    description: 'Lavatorio de loza de gran tamaño, formato italiano. Diseño amplio ideal para baños completos. Loza blanca de primera calidad con terminación brillante.',
    features: ['Loza sanitaria de 1ra. calidad', 'Formato grande italiano', 'Agujero para grifería central', 'Color blanco brillante', 'Compatible con la mayoría de griferías'],
    isFeatured: true,
  },
];
