import { Product, Category } from './types';

export const CATEGORIES: Category[] = [
  {
    id: 'obra-gruesa',
    name: 'Obra Gruesa',
    icon: '🏗️',
    image: 'https://images.unsplash.com/photo-1504307651254-35680f356dfd?auto=format&fit=crop&q=80&w=600',
    description: 'Cemento, hierro, bloques, membranas y materiales estructurales',
  },
  {
    id: 'pinturas',
    name: 'Pinturas',
    icon: '🎨',
    image: 'https://images.unsplash.com/photo-1562259949-e8e7689d7828?auto=format&fit=crop&q=80&w=600',
    description: 'Látex interior y exterior, esmaltes, fondos y selladores',
  },
  {
    id: 'instalaciones',
    name: 'Instalaciones',
    icon: '🔧',
    image: 'https://images.unsplash.com/photo-1621905251189-08b45d6a269e?auto=format&fit=crop&q=80&w=600',
    description: 'Plomería, calefacción, gas, electricidad y termotanques',
  },
  {
    id: 'herramientas',
    name: 'Herramientas',
    icon: '🔨',
    image: 'https://images.unsplash.com/photo-1504148455328-c376907d081c?auto=format&fit=crop&q=80&w=600',
    description: 'Amoladoras, taladros, sierras y herramientas profesionales',
  },
  {
    id: 'pisos',
    name: 'Pisos y Revestimientos',
    icon: '🧱',
    image: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?auto=format&fit=crop&q=80&w=600',
    description: 'Porcelanatos, cerámicas y revestimientos para cada ambiente',
  },
  {
    id: 'griferia',
    name: 'Grifería',
    icon: '🚿',
    image: 'https://images.unsplash.com/photo-1584622650111-993a426fbf0a?auto=format&fit=crop&q=80&w=600',
    description: 'Monocomandos, duchas y accesorios de alta calidad',
  },
  {
    id: 'sanitarios',
    name: 'Sanitarios',
    icon: '🚽',
    image: 'https://images.unsplash.com/photo-1552321554-5fefe8c9ef14?auto=format&fit=crop&q=80&w=600',
    description: 'Inodoros, bidets, lavatorios y vanitorios',
  },
  {
    id: 'ofertas',
    name: 'Ofertas',
    icon: '🏷️',
    image: 'https://images.unsplash.com/photo-1607082348824-0a96f2a4b9da?auto=format&fit=crop&q=80&w=600',
    description: 'Los mejores precios en productos seleccionados',
  },
];

export const PRODUCTS: Product[] = [
  // ── OBRA GRUESA ──────────────────────────────────────────
  {
    id: 'p1',
    name: 'Cemento Portland Loma Negra CPN40 x50kg',
    brand: 'Loma Negra',
    category: 'Obra Gruesa',
    subcategory: 'Cementos y Cales',
    price: 12500,
    listPrice: 12500,
    cashPrice: 10625,
    installments: 9,
    installmentPrice: 1389,
    image: 'https://images.unsplash.com/photo-1504307651254-35680f356dfd?auto=format&fit=crop&q=80&w=400',
    stock: true,
    stockStatus: 'in_stock',
    sku: 'CM-LN50',
    description: 'Cemento Portland Normal CPN40 de Loma Negra. El cemento más utilizado en la construcción general. Bolsa de 50kg con empaque resistente a la humedad. Ideal para hormigones, morteros y revoques en obras de todo tipo.',
    features: [
      'Tipo CPN40 — resistencia garantizada',
      'Bolsa con protección anti-humedad',
      'Fraguado uniforme y controlado',
      'Ideal para hormigón, revoques y morteros',
      'Disponible en pallets de 40 bolsas',
    ],
    isFeatured: true,
  },
  {
    id: 'p2',
    name: 'Hierro Corrugado Acindar Ø12mm x12m',
    brand: 'Acindar',
    category: 'Obra Gruesa',
    subcategory: 'Hierros y Aceros',
    price: 22800,
    listPrice: 22800,
    cashPrice: 19380,
    installments: 9,
    installmentPrice: 2533,
    image: 'https://images.unsplash.com/photo-1504328345606-18bbc8c9d7d1?auto=format&fit=crop&q=80&w=400',
    stock: true,
    stockStatus: 'in_stock',
    sku: 'HR-AC12',
    description: 'Varilla de hierro corrugado Acindar diámetro 12mm, longitud 12 metros. Material esencial para hormigón armado en losas, columnas y vigas. Certificado IRAM, alta resistencia a la tracción y flexión.',
    features: [
      'Diámetro 12mm certificado IRAM',
      'Longitud estándar 12 metros',
      'Alta resistencia a la tracción',
      'Apto hormigón armado estructural',
      'Marca Acindar — fabricación nacional',
    ],
    isFeatured: true,
  },
  {
    id: 'p3',
    name: 'Block Hormigón Estructural 20x20x40 (pallet x100 u.)',
    brand: 'Bloquera Mendoza',
    category: 'Obra Gruesa',
    subcategory: 'Bloques y Ladrillos',
    price: 95000,
    listPrice: 95000,
    cashPrice: 80750,
    installments: 9,
    installmentPrice: 10556,
    image: 'https://images.unsplash.com/photo-1589939705384-5185137a7f0f?auto=format&fit=crop&q=80&w=400',
    stock: true,
    stockStatus: 'in_stock',
    sku: 'BL-H100',
    description: 'Pallet de 100 unidades de block de hormigón estructural 20x20x40cm. Fabricación local mendocina con áridos de primera calidad. Resistencia H-16 garantizada para muros portantes y tabiques.',
    features: [
      '100 unidades por pallet',
      'Resistencia H-16 certificada',
      'Fabricación local Mendoza',
      'Apto para muros portantes',
      'Entrega con autoelevador incluida',
    ],
    isFeatured: true,
  },
  {
    id: 'p4',
    name: 'Membrana Asfáltica Aluminio Ormiflex 4mm x10m²',
    brand: 'Ormiflex',
    category: 'Obra Gruesa',
    subcategory: 'Impermeabilizantes',
    price: 48500,
    listPrice: 48500,
    cashPrice: 41225,
    installments: 9,
    installmentPrice: 5389,
    image: 'https://images.unsplash.com/photo-1581094794329-c8112a89af12?auto=format&fit=crop&q=80&w=400',
    stock: true,
    stockStatus: 'low_stock',
    sku: 'MB-OR4',
    description: 'Membrana asfáltica con terminación de aluminio, 4mm de espesor. Solución definitiva para impermeabilización de techos, terrazas y losas. Alta resistencia a rayos UV y variaciones térmicas.',
    features: [
      'Espesor 4mm reforzado con poliéster',
      'Terminación aluminio reflectiva',
      'Resistente a rayos UV y calor',
      'Aplicación a soplete de gas',
      'Rollo de 10m² por unidad',
    ],
    discount: 8,
    isFeatured: true,
  },
  {
    id: 'p5',
    name: 'Mortero Seco Weber Pro Revoque x30kg',
    brand: 'Weber',
    category: 'Obra Gruesa',
    subcategory: 'Morteros y Revoques',
    price: 8200,
    listPrice: 8200,
    cashPrice: 6970,
    installments: 9,
    installmentPrice: 911,
    image: 'https://images.unsplash.com/photo-1590424693420-e6a6c3a48c9e?auto=format&fit=crop&q=80&w=400',
    stock: true,
    stockStatus: 'in_stock',
    sku: 'MR-WB30',
    description: 'Mortero seco listo Weber Pro para revoques interiores y exteriores. Formulación con cal, cemento y áridos seleccionados. Solo agregar agua. Rendimiento de 18-20m² por bolsa a 2cm de espesor.',
    features: [
      'Bolsa 30kg lista para mezclar',
      'Rinde 18-20m² a 2cm de espesor',
      'Apto interior y exterior',
      'Fraguado controlado',
      'Aplicación manual o mecánica',
    ],
    isFeatured: false,
  },

  // ── PINTURAS ─────────────────────────────────────────────
  {
    id: 'p6',
    name: 'Pintura Látex Exterior Premium Tersuave 20L',
    brand: 'Tersuave',
    category: 'Pinturas',
    subcategory: 'Látex Exterior',
    price: 68000,
    listPrice: 68000,
    cashPrice: 57800,
    installments: 9,
    installmentPrice: 7556,
    image: 'https://images.unsplash.com/photo-1562259949-e8e7689d7828?auto=format&fit=crop&q=80&w=400',
    stock: true,
    stockStatus: 'in_stock',
    sku: 'PT-TE20',
    description: 'Pintura látex exterior premium Tersuave en balde de 20 litros. Alta cobertura con formulación antihongos y resistencia a la intemperie. Rendimiento de hasta 80m² por mano en superficie lisa.',
    features: [
      '20 litros — alta cobertura',
      'Protección antihongos y algas',
      'Resistente a lluvia, sol y granizo',
      'Rinde hasta 80m² por mano',
      'Secado 2hs — retoque en 4hs',
    ],
    discount: 12,
    isFeatured: true,
  },
  {
    id: 'p7',
    name: 'Esmalte Sintético Brillante Sinteplast 4L',
    brand: 'Sinteplast',
    category: 'Pinturas',
    subcategory: 'Esmaltes',
    price: 28500,
    listPrice: 28500,
    cashPrice: 24225,
    installments: 9,
    installmentPrice: 3167,
    image: 'https://images.unsplash.com/photo-1572981779307-38b8cabb2407?auto=format&fit=crop&q=80&w=400',
    stock: true,
    stockStatus: 'in_stock',
    sku: 'ES-SP4',
    description: 'Esmalte sintético brillante Sinteplast de 4 litros para maderas, hierros y metales. Excelente adherencia sin imprimación previa. Acabado brillante de larga duración resistente a la intemperie.',
    features: [
      'Para maderas y metales',
      'Acabado brillante de larga duración',
      'Alta resistencia a la intemperie',
      'Buena adherencia sin imprimación',
      '4 litros rinden 40-50m²',
    ],
    isFeatured: false,
  },
  {
    id: 'p8',
    name: 'Fijador Consolidante Poxipol 4L',
    brand: 'Poxipol',
    category: 'Pinturas',
    subcategory: 'Fondos y Selladores',
    price: 18900,
    listPrice: 18900,
    cashPrice: 16065,
    installments: 9,
    installmentPrice: 2100,
    image: 'https://images.unsplash.com/photo-1504307651254-35680f356dfd?auto=format&fit=crop&q=80&w=400',
    stock: true,
    stockStatus: 'in_stock',
    sku: 'FJ-PX4',
    description: 'Fijador consolidante Poxipol para superficies débiles y absorbentes. Prepara paredes, revoques y cielorrasos antes de pintar. Penetra en profundidad consolidando superficies friables.',
    features: [
      'Penetra y consolida en profundidad',
      'Reduce la absorción de la superficie',
      'Apto para revoque y mampostería',
      'Mejora la adherencia de pinturas',
      'Listo para pintar en 2 horas',
    ],
    isFeatured: false,
  },

  // ── INSTALACIONES ─────────────────────────────────────────
  {
    id: 'p9',
    name: 'Termotanque a Gas Rheem 80L Multigas',
    brand: 'Rheem',
    category: 'Instalaciones',
    subcategory: 'Termotanques',
    price: 285000,
    listPrice: 285000,
    cashPrice: 242250,
    installments: 18,
    installmentPrice: 15833,
    image: 'https://images.unsplash.com/photo-1585771724684-38269d6639fd?auto=format&fit=crop&q=80&w=400',
    stock: true,
    stockStatus: 'in_stock',
    sku: 'TT-RH80',
    description: 'Termotanque a gas de 80 litros Rheem multigas (natural y envasado). Cuba en acero esmaltado con ánodo de magnesio anti-corrosión. Piloto permanente con termopar de seguridad. Garantía 7 años de fábrica.',
    features: [
      '80 litros de capacidad',
      'Compatible gas natural y envasado',
      'Ánodo de magnesio anti-corrosión',
      'Piloto permanente con termopar',
      'Garantía 7 años de fábrica',
    ],
    isNew: true,
    isFeatured: true,
  },
  {
    id: 'p10',
    name: 'Caño PVC Presión Tigre 1" x6m',
    brand: 'Tigre',
    category: 'Instalaciones',
    subcategory: 'Plomería',
    price: 5800,
    listPrice: 5800,
    cashPrice: 4930,
    installments: 9,
    installmentPrice: 644,
    image: 'https://images.unsplash.com/photo-1621905251189-08b45d6a269e?auto=format&fit=crop&q=80&w=400',
    stock: true,
    stockStatus: 'in_stock',
    sku: 'PV-TG1',
    description: 'Caño PVC rígido para instalaciones de agua fría a presión. Diámetro 1" (25mm), longitud 6 metros. Certificado IRAM 13651. Compatible con todos los accesorios de la línea Tigre.',
    features: [
      'Diámetro 1" (25mm) normalizado',
      '6 metros de longitud',
      'Certificado IRAM 13651',
      'Alta resistencia a la presión',
      'Compatible accesorios Tigre',
    ],
    isFeatured: false,
  },

  // ── HERRAMIENTAS ─────────────────────────────────────────
  {
    id: 'p11',
    name: 'Amoladora Angular Bosch GWS 9" 2200W',
    brand: 'Bosch',
    category: 'Herramientas',
    subcategory: 'Amoladoras',
    price: 185000,
    listPrice: 185000,
    cashPrice: 157250,
    installments: 9,
    installmentPrice: 20556,
    image: 'https://images.unsplash.com/photo-1504148455328-c376907d081c?auto=format&fit=crop&q=80&w=400',
    stock: true,
    stockStatus: 'in_stock',
    sku: 'AM-BOS9',
    description: 'Amoladora angular Bosch profesional disco 9" (230mm) y 2200W de potencia. Empuñadura ergonómica, protector regulable, arranque suave y freno electrónico del husillo. La elegida por profesionales de la construcción.',
    features: [
      'Disco 9" (230mm)',
      '2200W — potencia profesional',
      'Arranque suave electrónico',
      'Freno electrónico del husillo',
      'Protector ajustable 360°',
    ],
    isNew: true,
    isFeatured: true,
  },
  {
    id: 'p12',
    name: 'Taladro Percutor DeWalt DWD024 650W',
    brand: 'DeWalt',
    category: 'Herramientas',
    subcategory: 'Taladros',
    price: 98000,
    listPrice: 98000,
    cashPrice: 83300,
    installments: 9,
    installmentPrice: 10889,
    image: 'https://images.unsplash.com/photo-1572981779307-38b8cabb2407?auto=format&fit=crop&q=80&w=400',
    stock: true,
    stockStatus: 'low_stock',
    sku: 'TD-DW650',
    description: 'Taladro percutor DeWalt 650W con portabrocas de 13mm y función percusión. Velocidad variable con inversión de marcha. Ideal para hormigón, mampostería, madera y acero. Incluye maletín.',
    features: [
      '650W — velocidad variable',
      'Portabrocas 13mm sin llave',
      'Función percusión para hormigón',
      'Inversión de marcha',
      'Incluye maletín de transporte',
    ],
    isFeatured: false,
  },

  // ── PISOS ─────────────────────────────────────────────────
  {
    id: 'p13',
    name: 'Porcelanato Cemix Dark 60x60 1ra. Cal.',
    brand: 'Cemix',
    category: 'Pisos y Revestimientos',
    subcategory: 'Porcelanatos',
    price: 181694,
    listPrice: 181694,
    cashPrice: 154440,
    installments: 9,
    installmentPrice: 20188,
    image: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?auto=format&fit=crop&q=80&w=400',
    stock: true,
    stockStatus: 'in_stock',
    sku: 'PD-060',
    description: 'Porcelanato de primera calidad en tono oscuro tipo cemento industrial. Ideal para ambientes modernos y minimalistas, tanto en interiores como exteriores cubiertos. Borde rectificado para juntas mínimas.',
    features: [
      'Tono oscuro tipo cemento',
      'Borde rectificado de fábrica',
      'Baja absorción de agua',
      'Resistente a alto tránsito',
      'Apto interior y exterior cubierto',
    ],
    isNew: true,
    isFeatured: true,
  },
  {
    id: 'p14',
    name: 'Cerámica Allpa California Gris 36x36',
    brand: 'Allpa',
    category: 'Pisos y Revestimientos',
    subcategory: 'Cerámicas',
    price: 215885,
    listPrice: 215885,
    cashPrice: 183602,
    installments: 9,
    installmentPrice: 23987,
    image: 'https://images.unsplash.com/photo-1615971677499-5467cbab01d5?auto=format&fit=crop&q=80&w=400',
    stock: true,
    stockStatus: 'low_stock',
    sku: 'CA-036',
    description: 'Cerámica gris claro diseño California, perfecta para ambientes luminosos. Formato 36x36cm que facilita la colocación y reduce el desperdicio. Acabado mate elegante para pisos de alto tránsito.',
    features: [
      'Acabado mate elegante',
      'Formato 36x36 cm',
      'Color gris claro uniforme',
      'Baja porosidad',
      'Fácil mantenimiento',
    ],
    discount: 10,
    isFeatured: true,
  },

  // ── GRIFERÍA ──────────────────────────────────────────────
  {
    id: 'p15',
    name: 'Monocomando Vasser Lyra Alto Lavatorio',
    brand: 'Vasser',
    category: 'Grifería',
    subcategory: 'Baño',
    price: 184620,
    listPrice: 184620,
    cashPrice: 156927,
    installments: 9,
    installmentPrice: 20514,
    image: 'https://images.unsplash.com/photo-1584622650111-993a426fbf0a?auto=format&fit=crop&q=80&w=400',
    stock: true,
    stockStatus: 'in_stock',
    sku: 'VL-001',
    description: 'Monocomando de diseño moderno para lavatorio. Tecnología cerámica de cierre suave, cuerpo de latón de alta durabilidad. Línea Lyra Alto de Vasser, perfecta para baños contemporáneos.',
    features: [
      'Cierre cerámico de alta durabilidad',
      'Cuerpo de latón 100%',
      'Acabado cromo brillante',
      'Fácil instalación',
      'Garantía 5 años de fábrica',
    ],
    isFeatured: true,
  },
  {
    id: 'p16',
    name: 'Ducha Monocomando Ext. Roca L20',
    brand: 'Roca',
    category: 'Grifería',
    subcategory: 'Duchas',
    price: 220921,
    listPrice: 220921,
    cashPrice: 187783,
    installments: 9,
    installmentPrice: 24547,
    image: 'https://images.unsplash.com/photo-1585704032915-c3400ca199e7?auto=format&fit=crop&q=80&w=400',
    stock: true,
    stockStatus: 'in_stock',
    sku: 'DR-L20',
    description: 'Monocomando externo para ducha de la reconocida línea L20 de Roca. Tecnología de ahorro de agua, diseño moderno y compatible con sistemas de ducha estándar. Latón cromado de alta durabilidad.',
    features: [
      'Tecnología de ahorro de agua',
      'Acabado cromado resistente',
      'Instalación externa simplificada',
      'Compatible con baterías estándar',
      'Marca Roca — garantía internacional',
    ],
    isFeatured: false,
  },
];
